version: 2
updates:
  # Update all dependencies in package.json files
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:10"
      timezone: "Europe/Paris"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Paris"
