version: "3.8"

services:
  node:
    image: node:21.1-alpine
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node
